spring.application.name=get-the-look-backend

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/get_the_look
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
